### ISSUE TITLE
Client-side error: WebSocket not present in global scope and no wsConstructor option was provided

### ISSUE THREAD

**Issue by pcowgill** [blocknative/sdk#101]
I'm getting a `WebSocket not present in global scope and no wsConstructor option was provided` error in a React app built with Next.js that's using the `bnc-sdk` npm package. The docs say the `ws` option is only needed on a server. Any ideas? Thanks!

**Comment by cmeisl** [comment]
Are you getting this error in the context of client rendered code in the browser (which should automatically provide a wevbsocket environment) or are you using server side rendering which may require injection a ws object?

**Comment by pcowgill** [comment]
> Are you getting this error in the context of client rendered code in the browser (which should automatically provide a wevbsocket environment) or are you using server side rendering which may require injection a ws object?

It should be the client-rendered code - I'm setting it up in a React context provider. But it's possible Next.js is somehow involving the server at this root level.

**Comment by pcowgill** [comment]
This seems promising
```
const isBrowser = typeof window !== 'undefined';
if (!blocknative && isBrowser) {
  // initialize and connect to the api
  blocknative = new Blocknative(options);
}
```

**Comment by aaronbarnardsound** [comment]
@pcowgill Yep that would be the way to go when working with Next.js 👍

**Comment by aaronbarnardsound** [comment]
Closing this issue as it seems to be resolved.
