### ISSUE TITLE
Unable to see mempool events via sdk

### ISSUE THREAD

**Issue by vaibhavk97** [blocknative/sdk#131]
Hi, I am unable to see mempool events via sdk. Kindly let me know if anything is wrong with the following piece of code. 

```js 
const BlocknativeSdk = require('bnc-sdk');
const WebSocket = require('ws');

const options = {
    dappId: 'caexxxxx-28da-xxx-9c7d-xxxxxxx',
    networkId: 56,
    ws: WebSocket,
	onerror: function(error) { console.error(error); },
    onopen: function(){ console.log("WS Connected!!"); }
  }
  
  const blocknative = new BlocknativeSdk(options)

  const registerBlocknative = (address) => {

	const { emitter } = blocknative.account(address)
	
	emitter.on('all', transaction => {
		console.log('emit 1');
		var tx = {
			status: transaction.status,
			value: transaction.value,
			timeStamp: transaction.timeStamp,
			gasPriceGwei: transaction.gasPriceGwei,
			contractCall: transaction.contractCall
		};
		console.log(transaction);
	});
}

registerBlocknative("0x10ED43C718714eb63d5aA57B78B54704E256024E")
```

**Comment by taylorjdawson** [comment]
Hey @vaibhavk97! I'll test this in a bit and get back to you, the code itself looks like it should work. How long did you run this for?

**Comment by vaibhavk97** [comment]
I ran this for a few minutes, mempool explorer in browser reports transactions correctly. However, the code doesn't.

**Comment by taylorjdawson** [comment]
@vaibhavk97 what gets logged to the console?

**Comment by vaibhavk97** [comment]
```
vaiku@Cyril:~/BSC/src$ node scratch.js 
WS Connected!!
````
And then it keeps listening for an event which is never emmitted.

**Comment by vaibhavk97** [comment]
I checked a bit further, the code is working for Uniswap router address and networkId 1. Looks like this issue is specific to Binance smart chain (networkId 56).

**Comment by vaibhavk97** [comment]
Figuered out the Issue, I was using an old version of the bnc-sdk, it works fine upon updation. Thanks for your support.
