### ISSUE TITLE
For `txConfirmed` the api now returns `timePending` as an int and not as a string

### ISSUE THREAD

**Issue by krasi-georgiev** [blocknative/sdk#145]
As per the docs and the other TX codes the `timePending` should be returned as a string, but `txConfirmed` returns it as an int. Can you please return int for all TX types or change it to string to make it consistent for json unmarshaling.

**Comment by aaronbarnardsound** [comment]
Hey @krasi-georgiev thanks for pointing this out. It looks like the Blocknative server is returning a `number` type for the `timePending` field for `pending-simulation` status events when it should be a `string`. We will get a fix deployed to the server asap and I will comment here once it is live.

**Comment by krasi-georgiev** [comment]
Thanks. Any ETA on when to expect the fix deployed on production?

**Comment by aaronbarnardsound** [comment]
Hey @krasi-georgiev a fix is deployed to production. It turned out that the `timePending` field for `pending-simulation` actually doesn't make any sense, so we have removed it from payloads with that status. All other `timePending` values should be a string as documented.

**Comment by krasi-georgiev** [comment]
still getting `timePending` as an int for some events

**Comment by krasi-georgiev** [comment]
I think it is actually exactly stil for `pending-simulation`

**Comment by aaronbarnardsound** [comment]
Tagging @alexcampbelling here so he can take another look as the API should have been updated with the fix.

**Comment by alexcampbelling** [comment]
Heya @krasi-georgiev! A fix has now been deployed and I will close this issue. Thanks for bringing this up!

**Comment by krasi-georgiev** [comment]
would you mind linking the PR or commit to see the new implementation?
