### ISSUE TITLE
Exception in browser environment when cookies are blocked

### ISSUE THREAD

**Issue by freeatnet** [blocknative/sdk#171]
**Steps to reproduce:**

1. Open a website that uses `bnc-sdk` (for example, https://reactdemo.blocknative.com/) in the browser of your choice.
2. Note that the website works as expected.
3. Block cookies from the website.
4. Reload the page if necessary.

**Expected:** the website experience may be degraded, but the website works.
**Observed:** a `SecurityError` exception that happens in `bnc-sdk` prevents the website from functioning. Some browsers seem to set `window.localStorage` to `null` when cookies are blocked instead of throwing a `SecurityError`, causing a `TypeError: null is not an object`.

Some initial triage: Exceptions happen in two places in `bnc-sdk`: in the `Blocknative` constructor [here](https://github.com/blocknative/sdk/blob/7fc29c334ad7186f2b62bebeefab79a4fce79669/src/index.ts#L116) and in `handleMessage` [here](https://github.com/blocknative/sdk/blob/8202a07f739ab939d682e5dabeec8726347f8152/src/messages.ts#L67).

It looks like both pieces of code are designed to work even when `LocalStorage` is not available. Is it safe to ignore the data at `_storageKey` in-browser when `window.localStorage` is not available? I'm happy to contribute a patch here.

**Comment by Adamj1232** [comment]
Closing with your PR release in 4.1.0 Thanks you @freeatnet ! Have a great weekend!!
